# Generated by Django 5.1 on 2024-08-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyapp1', '0003_filerenamehistory_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerenamehistory',
            name='epoch',
            field=models.IntegerField(default=1723189606),
        ),
    ]
