# Generated by Django 5.1 on 2024-08-09 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyapp1', '0005_filerenamehistory_new_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secret_key', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='filerenamehistory',
            name='epoch',
            field=models.IntegerField(default=1723199949),
        ),
    ]
