# Generated by Django 5.1 on 2024-08-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyapp1', '0006_client_alter_filerenamehistory_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerenamehistory',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shyapp1.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filerenamehistory',
            name='epoch',
            field=models.IntegerField(default=1723200854),
        ),
    ]
