# Generated by Django 5.1 on 2024-08-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyapp1', '0007_filerenamehistory_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerenamehistory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shyapp1.client'),
        ),
        migrations.AlterField(
            model_name='filerenamehistory',
            name='epoch',
            field=models.IntegerField(default=1723201022),
        ),
    ]
