# Generated by Django 5.1 on 2024-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyapp1', '0008_alter_filerenamehistory_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerenamehistory',
            name='epoch',
            field=models.IntegerField(default=1723201360),
        ),
    ]
